### ISSUE TITLE
pass update

### ISSUE THREAD

**Issue by roddhjav** [SirCmpwn/pass-rotate#10]
Hi all,

I have been working for a while on a very similar system in the form of a pass extension, [pass update](https://github.com/roddhjav/pass-update). I just published on github my work so you can see the (still work in progress) program on the branch `auto`.

My system uses:
- Selenium webdriver for easy browser interaction
- YAML file for website support (called instance because the data are the same either it is `gitlab.com` or every gitlab instances). See my [yaml doc](https://github.com/roddhjav/pass-update/blob/auto/YML.md)
- Full pass integration (well, it is a pass extension). It is actually the biggest part. Because the rotate system is quite simple. See [updater.py](https://github.com/roddhjav/pass-update/blob/auto/updaters/updater.py#L167)
- Provides a dedicated password store wrapper. (WIP)

I'd like to have comments from you guys. Also because it does not make sense to have two different (concurrent) program, it could be interesting to merge them (taking the best of the two world).

**Comment by SirCmpwn** [comment]
Took a look at your YAML docs. Neat idea, but I think it's better served by Python modules so that we can handle niche edge cases. Some of the providers we already support would be difficult to handle with your YAML spec ([namecheap](https://github.com/SirCmpwn/pass-rotate/blob/master/passrotate/providers/namecheap.py), for example).

I think we will need to use selenium to support some providers, and I'll be experimenting with this soon.

As for the future of your project, it might make sense to rejigger it into a project that integrates with pass-rotate to do the actual rotation and provides pass-specific functionality?

**Comment by roddhjav** [comment]
> I think it's better served by Python modules so that we can handle niche edge cases.

It is unmaintainable to only have python code for the support of all the instance. Moreover, YML allow to handle special update process where for instance the website ask the user to go to a few different page. For more complex website it could still be possible to provide a python module.

Moreover, using YML file (and selenium) allow us to have a very simple update code ([10 lines](https://github.com/roddhjav/pass-update/blob/auto/updaters/updater.py#L167))

> As for the future of your project, it might make sense to rejigger it into a project that integrates with pass-rotate to do the actual rotation and provides pass-specific functionality?

I'm perfectly agree on this point, pass-rotate provides the updater library, pass-update provides the integration with `pass`.

That said. If you need help with the update process, I'm here, moreover, the actual stage of pass-update could provide new idea...

**Comment by SirCmpwn** [comment]
>It is unmaintainable to only have python code for the support of all the instance.

Why is that unmaintainable?

>Moreover, using YML file (and selenium) allow us to have a very simple update code (10 lines)

Sure, but yours doesn't support a lot of use-cases. In my experience so far, the norm is for websites to be weird, not simple, and custom code would be required a lot. Also, using selenium for *everything* is overkill and will significantly slow down the process of rotating a lot of passwords at once. We should only resort to it for websites that are just too complicated to reverse engineer and do in Python (i.e. Amazon) - cases where it's doing a lot of work in JavaScript, has anti-bot measures (PayPal, Patreon), etc.

**Comment by SirCmpwn** [comment]
A suggestion for pass-update, by the way: currently if setting the user's password fails in `execute`, the new password will have already been set in pass.

**Comment by SirCmpwn** [comment]
I think the best way to fix that might be to switch away from using `gen-password` to `set-password` or something, then having pass-rotate decide what the new password should be. Then we can write complexity requirements into pass-rotate for example.

**Comment by roddhjav** [comment]
> Why is that unmaintainable?

It is more complex (and therefore not KISS). An example, for the (simple) case of github:
* With [python module](https://github.com/SirCmpwn/pass-rotate/blob/master/passrotate/providers/github.py)
* With [yml file](https://github.com/roddhjav/pass-update/blob/auto/updaters/instances/github.com.yml)

That said my system does not support complex workflow. But the yml parser should be able to be improved in order to support them. The worst case scenario would be to have a yml file that just contains a `module: True` to switch back to a python module. (could also support both).

For the selenium support only in complex case, you're right, but it is not incompatible with the use of yml file.

> A suggestion for pass-update, by the way: currently if setting the user's password fails in execute, the new password will have already been set in pass.

This part is not finished, actually the system is not yet able to overwrite the password, and the code relating to that is commented. (only because the pass wrapper is not finished).

**Comment by SirCmpwn** [comment]
>It is more complex (and therefore not KISS).

Only marginally so, but that still doesn't make it unmaintainable. What sounds unmaintainable to me is maintaining a selenium driver + YAML format that is extended to support enough situations to cover all of the weird edge cases we're definitely going to see.

The Python code is quite clean and approachable to people who know even an entry-level amount of Python, imo. It's perfectly maintainable. Adding a YAML system on top of this *increases* complexity where it matters and decreases complexity where it doesn't.

**Comment by SirCmpwn** [comment]
The YAML file is also effectively a DSL, which has a greater cognitive load on people learning the codebase so they can contribute.

**Comment by roddhjav** [comment]
You're right, unmaintainable is not the term (sorry for that). But because the purpose of this project is to support a lot of websites/instances. The use of YAML file provide an easier to contribute.

**Comment by roddhjav** [comment]
After, it is our work to find a YAML format complex enough to support complex case, and still easy to maintain.

**Comment by SirCmpwn** [comment]
I disagree. It makes it harder to contribute. I imagine that the average contributor already knows Python and already knows how to use requests, but does not know how to write one of your YAML files.

>it is our work to find a YAML format complex enough to support complex case, and still reasonable easy to maintain

This is an oxymoron.

**Comment by roddhjav** [comment]
In my opinion, the use of yml file is the *right tool* to do the job.

That said it is your project although I did the same project on my side, yours is more advanced. Therefore I won't continue the automatic update part on mine. However, as said earlier I will continue pass update but on the pass extension side. Where pass-rotate provides the library, pass-update provides the integration with pass.

**Comment by SirCmpwn** [comment]
Sounds good. I think we've got everything we need from this issue.
