### ISSUE TITLE
Add more flexible form extraction functions

### ISSUE THREAD

**Issue by adelq** [SirCmpwn/pass-rotate#19]
The current form extraction function is highly inflexible, especially with weird forms that have no distinguishing properties. I ran into this problem for both the Zotero and PyPI providers.

Possible solutions to have a more flexible API for `get_form`:
 - Add another function that uses CSS selectors
 - Add keyword argument to pass in an arbitrary function to apply to the soup

Example of how this could work:

```python
def custom_get_form(text, func, **kwargs):
    """Pass in func that works on a soup and outputs input fields"""
    soup = BeautifulSoup(text, "html5lib")
    inputs = func(soup)
    data = {
        i.get("name", ""): i.get("value", "") or "" for i in inputs if i.get("name", "")
    }
    return data

custom_get_form(r.text, lambda s: s.find(id="content").find("form").find_all("input"))
```

This method should be flexible enough to allow the entire API of BeautifulSoup to be used by providers without duplicating the data extraction. Thoughts?

**Comment by SirCmpwn** [comment]
I like it.
