### ISSUE TITLE
Passwords are generated in-place

### ISSUE THREAD

**Issue by gabm** [SirCmpwn/pass-rotate#32]
The passwords are currently generated in-place in advance. If password-changing fails, then we have the new password in the pass store but still the old password on the website...

I have two strategies in mind:

1. keep generating the password in-place but carefully catch any exceptions and store the old password if necessary
2. only generate the password, change it and then store it into the pass-store

Somehow I prefer the 2nd solution but I'm not sure whether its possible/desirable to do so... What worries me about the 1st solution is: What happens if the user aborts somewhere - or the program crashes. Then we can never rewind even though an "error" occured...

This is related to #31 because it interferes with handling the exceptions. I'll provide a solution to this together with/after implementing the custom exceptions

**Comment by SirCmpwn** [comment]
Some password managers (notably `pass`) cannot generate passwords without storing them. This drove the current design.

**Comment by SirCmpwn** [comment]
(Therefore option 1 is probably good)

**Comment by gabm** [comment]
> (Therefore option 1 is probably good)

and the only option I'm afraid... apart from using an external generator...
