### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by arunisaac** [SirCmpwn/pass-rotate#34]
Hi,

I'd like to package pass-rotate for Guix. Guix prefers to package release tarballs. Other distros tend to have similar preferences. Could we have the first release of pass-rotate?

Thanks.

**Comment by SirCmpwn** [comment]
I'm not sure we have enough providers supported to justify a release.

**Comment by arunisaac** [comment]
Drew DeVault <notifications@github.com> writes:

> I'm not sure we have enough providers supported to justify a release.

It's true that we don't have enough providers. But, I don't think we
should decide on a release based on the number of providers we
have. Instead, it should be based on whether the CLI and user experience
is sufficiently stable, and unlikely to change. Providers can always be
added easily later.

Also, it's easier to gain traction with users if we have a release, and
pass-rotate is packaged for different distros.

Would at least a 0.1 release be justified at this point?

**Comment by arunisaac** [comment]
Sure, I'll send you a new provider within a week! :-)

**Comment by SirCmpwn** [comment]
As promised: https://github.com/SirCmpwn/pass-rotate/releases/tag/0.1

**Comment by arunisaac** [comment]
Thank you! Just for future reference, considering that our providers can
change frequently, maybe we should use date based version numbers like
youtube-dl does.

https://github.com/rg3/youtube-dl/releases

Not a big deal at the moment, but I just wanted to mention it.

**Comment by SirCmpwn** [comment]
Maybe once we hit a critical mass of providers we can change the scheme.
