### ISSUE TITLE
Explicitly specifying the provider to use in pass-rotate.ini

### ISSUE THREAD

**Issue by arunisaac** [SirCmpwn/pass-rotate#37]
There is a lot of self-hosted free software that could be hosted on any domain. For such services, deciding which provider to use based on the domain is a no go. We need a `provider` field that will allow the user to explicitly specify which provider to use.

What do you think? If we can agree on an implementation, I can implement it and provide a pull request.

**Comment by arunisaac** [comment]
How would auto-detection work? Even if we had auto-detection routines,
running a service against every auto-detector routine that we have
sounds like an O(n) problem.

**Comment by SirCmpwn** [comment]
We'd want to have some kind of cache so we don't e.g. redownload index.html all of the time. But O(n) is a good O to have, nothing wrong with O(n).

**Comment by arunisaac** [comment]
I was trying to implement a provider field as discussed. But then, I
realized that, as the code currently stands, I am already able to
explicitly specify the provider by putting the name of the provider in
the domain field.

Is this a desirable feature we should just document and be happy with?
Or should we scrap it and create a separate provider field in order to
not cause confusion?

Also, about auto-detection, I don't mind having it. But, I am a little
unsure of its utility. Even with auto-detection, we require the user to
specify the domain. Why not just require them to specify the provider
instead? It doesn't make a big difference to the user experience, IMO.

**Comment by SirCmpwn** [comment]
>Is this a desirable feature we should just document and be happy with?

Yeah let's do this.

>Also, about auto-detection, I don't mind having it. But, I am a little unsure of its utility. Even with auto-detection, we require the user to specify the domain. Why not just require them to specify the provider
instead?

pass-rotate is a library, too, think about the use-case where the user isn't interacting with it via the CLI and our config file but an integration with some other password manager instead.
